### ISSUE TITLE
After upgrading ratatui from 0.20.1 to 0.21.1: trait bound `TuiLoggerWidget<'_>: Widget` is not satisfied

### ISSUE THREAD

**Issue by lcmgh** [gin66/tui-logger#38]
```rust
error[E0277]: the trait bound `TuiLoggerWidget<'_>: Widget` is not satisfied
   --> src/ui.rs:125:21
    |
125 |     f.render_widget(tui_w, chunks[4]);
    |       ------------- ^^^^^ the trait `Widget` is not implemented for `TuiLoggerWidget<'_>`
    |       |
    |       required by a bound introduced by this call
    |
    = help: the following other types implement trait `Widget`:
              BarChart<'a>
              Canvas<'a, F>
              Chart<'a>
              Gauge<'a>
              LineGauge<'a>
              List<'a>
              Paragraph<'a>
              Sparkline<'a>
            and 4 others
```

```rust
    let tui_w: TuiLoggerWidget = TuiLoggerWidget::default()
        .block(
            Block::default()
                .title("Logs")
                .border_style(Style::default().fg(Color::White))
                .borders(Borders::ALL),
        )
        .output_separator('|')
        .output_timestamp(Some("%F %H:%M:%S".to_string()))
        .output_level(Some(TuiLoggerLevelOutput::Long))
        .output_target(false)
        .output_file(false)
        .output_line(false)
        .style_error(Style::default().fg(Color::Red))
        .style_debug(Style::default().fg(Color::Green))
        .style_warn(Style::default().fg(Color::Yellow))
        .style_trace(Style::default().fg(Color::Magenta))
        .style_info(Style::default().fg(Color::Cyan))
        .state(&app.states[0]);

// ..

f.render_widget(tui_w, chunks[4]);
```

**Comment by gin66** [comment]
I have updated to 0.21.0
But there is no 0.21.1 yet.

**Comment by lcmgh** [comment]
My mistake, of course latest ratatui is 0.21.0. Thanks for the fix.
